import { useState, useEffect } from "react";
import { Box, Typography } from "@mui/material";
import "./styles/map.css";

const noEventsMessages = [
  "🚁 The parking drones are taking a break",
  "👼 The parking angels have a day off",
  "🚦 Traffic jams untangled, but no events found",
  "✨ The parking spaces are all polished, just for you",
  "🚓 No illegal parkers today, all clear!",
  "🔄 Traffic signs rerouted to nowhere",
  "🔋 Parking tickets fully charged, but no events",
  "🎼 The parking lot orchestra is on a break",
  "🦄 The parking unicorns are grazing elsewhere",
  "🔍 No spots playing hide and seek today",
  "🍝 The parking lot spaghetti is untangled",
  "🚗 All cars have reached their destiny",
  "🕵️‍♂️ No parking spots to lure out today",
  "🤝 The parking lot gremlins are at peace",
  "🎈 No invisible parking spots inflated today",
  "🅿️ All cars know how to parallel park",
  "🧙‍♂️ The parking lot wizards are resting",
  "🌌 The parking lot dimensions are quiet",
  "🔍 No secret parking spots to unveil",
  "🎬 The parking show is on a break",
  "🌌 The stars have aligned, but no events",
  "🦸‍♂️ The parking superheroes are on vacation",
  "🦖 No dinosaurs in the parking spots",
  "👽 No alien parking today",
  "🚀 The parking satellites have no news",
  "🏰 Your parking castle is under construction",
  "🔮 The parking crystal ball shows no events",
  "🐉 The parking dragon is napping",
  "🌈 No parking at the end of the rainbow",
  "🧹 The parking spots are all clean",
  "🕹️ No Tetris with cars today",
  "🧩 The parking puzzle is complete",
  "📡 No new parking frequencies found",
  "🖼️ The parking masterpiece is in progress",
  "📦 The parking spots are all unpacked",
  "🔓 No premium parking to unlock",
  "🧬 The parking genes are in perfect order",
  "🗝️ The best spots are all taken",
  "🎨 The parking map is all drawn",
  "🔍 The perfect spot remains elusive",
  "🌲 No new parking spaces planted today",
  "🎠 The parking carousel is not spinning",
  "🎈 No new parking opportunities today",
  "🍭 No sweet parking deals today",
  "🎭 The parking traffic is directed elsewhere",
  "🎹 The parking symphony is silent",
  "🎨 No new parking maps to draw",
  "📸 No parking moments to capture",
  "🎡 The parking wheel is still",
  "🏅 No gold medal spots today",
  "🚀 The parking zones are all clear",
  "💫 No parking adventures today",
  "🎲 The parking dice are not rolling",
  "🎬 No new parking scenes to produce",
  "🎧 The parking jams are over",
  "🎷 The parking jazz session is done",
  "🎻 The best spots are playing their tune",
  "🎹 The parking keys are all hit",
  "🥁 The parking spots are drummed up",
  "🎻 The parking violin is put away",
  "🎙️ The parking news is quiet",
  "📼 No parking tapes to rewind",
  "🎥 No parking stories to film",
  "📡 The parking waves are silent",
  "🎇 The parking spots are not sparkling",
  "🎆 No parking magic today",
  "🌌 No parking galaxies to explore",
  "🌙 The parking guides are sleeping",
  "🌤️ The parking forecast is clear",
  "🔥 The parking is not heated up",
  "🌪️ No parking spots spinning up",
  "🌊 No parking waves to surf",
  "🗻 The parking peaks are calm",
  "🏢 The parking views are skyscraping",
  "🏗️ No new parking spots constructed",
  "🏚️ No parking spaces renovated",
  "🏘️ The parking spots are neighboring quietly",
  "🏖️ No beach parking today",
  "🏞️ The nature is finding your spot",
  "🔄 Your vehicle's destiny is adjusted",
  "📡 Connecting to space for the perfect spot",
  "🌌 Navigating the parking cosmos",
  "🔍 No hidden parking opportunities today",
  "📜 The parking treasure map is unrolled",
  "🔓 No secret parking spaces to unlock",
  "🧭 The compass is set to 'no parking'",
  "🧬 No perfect fit to decode",
  "🎯 The bullseye for spaces is missed",
  "🎞️ The last spot is rewound",
  "🧵 No available areas to weave through",
  "🔋 No prime locations to charge up",
  "🎶 The symphony of spots is silent",
  "📡 The horizons are scanned",
  "📦 No new possibilities to unpack",
  "🧱 No network of spaces to build",
  "📊 No best areas to chart",
  "🔎 The ideal locations remain hidden",
  "🚦 The smooth entries are coordinated",
  "🛤️ No best routes to track",
  "🔋 No available spots to recharge",
  "🎟️ No VIP passes issued",
  "📅 The optimal times are scheduled",
  "🔦 The opportunities are highlighted",
  "📜 The map is unfolded",
  "🌌 The layout is explored",
  "🔧 No settings to adjust",
  "🔒 The spots are secured",
  "📏 The distances are measured",
  "🔋 The options are powered up",
  "🔭 The landscape is surveyed",
  "📡 The signals are tracked",
  "🛠️ The selections are refined",
  "🔍 The hidden areas remain hidden",
  "📈 The course is plotted",
  "🔓 The best spots are unlocked",
  "📸 The perfect fit is captured",
  "🎨 The route is designed",
  "🎬 The best scenes are produced",
  "🔮 The availability is foreseen",
  "🔍 The optimal areas remain hidden",
  "🔧 The solution is perfected",
  "🎉 The grand event parking rush is prepared",
  "⭐ The VIP parking spots are aligned",
  "🌊 The parking waves are rolled in",
  "📞 The other side of the parking lot is quiet",
  "🌤️ Your car is in parking heaven",
  "🦕 No million-year-old parking today",
  "🔄 No tables turned to find a spot",
  "☔️ No fire to the rain or parking spots",
  "📡 No SOS for parking assistance",
  "⏳ The parking spot is almost found",
  "🧘 Finding you a parking spot is easy",
  "🔥 No parking struggles today",
  "👋 The perfect parking spot is found",
  "💖 Your car's parking space is loved",
  "🎶 No hallelujah for parking today",
  "📞 No call for parking spot needed",
  "⛓️‍💥 The parking melody is unchained",
  "🎵 We will park you, but not today",
  "🎤 No parking as sweet as Sweet Caroline",
  "👐 Lean on us, but no parking spot today",
  "🕵️‍♀️ No need to guess, no parking spot today",
  "🚀 The parking god is taking a break",
  "🎯 One shot missed for a great spot",
  "❤️ We love your parking, but no spots today",
  "📖 The parking story is paused",
  "🌈 Imagine all the parking, just not today",
  "❓ What's going on with finding your spot? Nothing!",
  "🌙 Night and day, no parking spot",
  "🌍 How many roads to find a spot? None today",
  "🤝 I promise, you'll park better, but not today",
  "❤️‍🔥 You're a parking guy, but no spots today",
  "😴 Can't sleep until I find your parking spot, which is none",
  "🤝 A spot to park with you, but not today",
  "👍 Good 4 u, finding no parking spot",
  "🪐 May the parking be with you, just not today",
  "🦸‍♂️ The Avengers are not assembling any spots",
  "🌍 No place like your parking spot, which is nowhere",
  "💔 Frankly, my dear, no parking today",
  "🎩 Looking at you, parking kid, but no spots",
  "🌟 May the force park with you, just not today",
  "🕶️ No parking today",
  "👽 E.T. found no parking spot",
  "🕸️ No friendly neighborhood parking spot",
  "🍫 Life is like a box of parking spots, just empty today",
  "🐴 You've got a friend in parking, but no spots",
  "📜 No parking offer you can't refuse",
  "🧟 They're coming to park, but not today",
  "👨‍🚀 Houston, no parking spot",
  "💍 My precious parking spot, which is none",
  "💡 Park hard or go home, but no spots today",
  "🐧 Just keep parking, but not today",
  "🕰️ I'll be back, but no parking spot",
  "⚡ You're a parking wizard, Harry, but not today",
  "🍿 I'll have what she's parking, which is nothing",
  "🎩 Keep your friends close, but no parking spots closer",
  "🚣 I'm the king of the parking lot, which is empty",
  "🕴️ I feel the need, the need to park, but not today",
  "🌌 In space, no one can hear you park, because there's no spot",
  "🪤 It's a parking trap, because there's no spot",
  "🍕 Hasta la vista, parking, because there's no spot",
  "🏴‍☠️ The day you parked, which is not today",
  "🌪️ There's no place like a parking spot, which is none",
  "🐯 Remember who you parked with, which is no one",
  "🏎️ Great Scott! No parking spot",
  "🎵 We don't talk about parking, because there's none",
  "🦖 Hold onto your parking spots, which are none",
  "🌄 Make my parking day, which is empty",
  "🎥 May the parking be ever in your favor, just not today",
  "🔍 Elementary, my dear parking, which is none",
  "🎞️ Park a hero or see yourself become a villain, which is neither today",
  "🦁 Long live the parking, which is empty",
  "🎹 All work and no parking, makes Jack a dull boy",
  "🧞‍♂️ No parking spot like this",
  "🧙‍♂️ You shall not park, because there's no spot",
  "🕶️ I see dead parking spots, because there's none",
  "👨‍🚀 This is ground control to parking spot, which is none",
  "🦈 We're gonna need a bigger parking lot, which is empty",
  "🍎 Here's Johnny, parking nothing",
  "🎩 Your parking spot is as big as mine, which is none",
  "🧛‍♂️ I'm Batman, and I parked nowhere",
  "🐢 It's not a parking, it's a spot, which is none",
  "🕷️ With great parking, comes great responsibility, but no spot",
  "🍻 I'll park what she's parking, which is nothing",
  "🐅 It's a jungle out there, for no parking",
  "🌋 Make my parking day, which is empty",
  "👑 The odds be ever in your favor, for no parking",
  "🎭 A parking spot to remember, which is none",
  "🎙️ A parking spot you can't refuse, which is none",
  "🧊 Keep your friends close, but no parking spots closer",
  "🦩 No parking in a corner",
  "🗻 A beautiful parking spot, which is none",
  "🦷 A little parking spot, which is none",
  "🏺 I am parking, but not today",
  "🛎️ Inconceivable parking, because there's none",
  "🗽 No parking for what she's parking",
  "🌇 An old friend for parking, but none",
  "🧳 Mister Parking found nothing",
  "🧦 It's a wonderful parking spot, which is none",
  "🏴‍☠️ Taking over the parking lot, which is empty",
  "🐡 Finding parking, which is none",
];

const NoEventsOverlay = () => {
  const [currentMessage, setCurrentMessage] = useState("");

  useEffect(() => {
    const getRandomMessage = () =>
      noEventsMessages[Math.floor(Math.random() * noEventsMessages.length)];

    const messageIntervalId = setInterval(() => {
      setCurrentMessage(getRandomMessage());
    }, 10000);

    setCurrentMessage(getRandomMessage());

    return () => clearInterval(messageIntervalId);
  }, []);

  return (
    <Box className="no-events-overlay">
      <Typography variant="h4" align="center">
        {currentMessage}
      </Typography>
    </Box>
  );
};

export default NoEventsOverlay;
